# $MCSROOT/etc/profile -*- Mode: shell-script -*-
# (c) jmmc


# Define VLTROOT to MCSROOT
export VLTROOT=$MCSROOT

# Add $MCSROOT to PATH
if ! echo ${PATH} |grep -q $MCSROOT ; then
    export PATH="$PATH:$INTROOT/bin:$MCSROOT/bin"
fi

# Set LD_LIBRARY_PATH (path for dynamic linked libraries)
export LD_LIBRARY_PATH=../lib:$INTROOT/lib:$MCSROOT/lib

# Aliases
alias m=more
alias gvim='gvim -geometry 80x45'
