/*
 * Error Include File    Created on ...
 *
 * This file has been generated by errXmlToH utility
 * 
 * !!!!!!!!!!!  DO NOT MANUALLY EDIT THIS FILE  !!!!!!!!!!!
 */

 /**
 * \file 
 * Generated file for the define list of errors.
 */
#define miscERR_NULL_PARAM 1   /**<  Received a NULL value for parameter '%80s'. */
#define miscERR_ALLOC 2   /**<  Could not allocate or copy memory. */
#define miscERR_FUNC_CALL 3   /**<  Could not perform '%80s' function call. */
#define miscERR_DYN_BUF_BAD_POSITION 4   /**<  '%80s' parameter outside of the Dynamic Buffer range. */
#define miscERR_DYN_BUF_BAD_FROM_TO 5   /**<  Received bad 'from' and 'to' parameters ('to' lower than 'from'). */
#define miscERR_DYN_BUF_COULD_NOT_READ_FILE 15   /**<  Could not read '%80s' file : '%80s'. */
#define miscERR_DYN_BUF_COULD_NOT_SAVE_FILE 21   /**<  Could not save '%80s' file : '%80s'. */
#define miscERR_DYN_BUF_NOT_INITIALIZED 23   /**<  Dynamic Buffer not initialized. */
#define miscERR_DYN_BUF_IS_EMPTY 24   /**<  Dynamic Buffer is empty. */
#define miscERR_FILE_ENV_VAR_NOT_DEF 6   /**<  '%80s' environment variable is not defined. */
#define miscERR_FILE_ENV_VAR_TOO_LONG 7   /**<  '%80s' environment variable is too long for the received buffer. */
#define miscERR_FILE_ENV_VAR_NOT_INT 30   /**<  '%80s' environment variable content '%80s' is not of integer type. */
#define miscERR_FILE_PERMISSION_DENIED 8   /**<  File '%80s' cannot be accessed : Permission Denied. */
#define miscERR_FILE_NAME_TOO_LONG 9   /**<  File '%80s' cannot be accessed : Too Long. */
#define miscERR_FILE_DOESNT_EXIST 10   /**<  File '%80s' cannot be accessed : Doesn't Exist. */
#define miscERR_FILE_TOO_MANY_SYM_LINKS 11   /**<  File '%80s' cannot be accessed : Too Many Symbolic Links. */
#define miscERR_FILE_UNDEFINED_ERRNO 12   /**<  File '%80s' cannot be accessed : errno='%d'. */
#define miscERR_FILE_EXTENSION_MISSING 14   /**<  File name '%80s' has no extension. */
#define miscERR_FILE_NOT_FOUND_IN_PATH 20   /**<  File '%80s' cannot be found in '%80s' path. */
#define miscERR_HASH_KEY_NOT_FOUND 16   /**<  Key '%.100s' not found in the Hash Table. */
#define miscERR_STRING_MAX_SUBSTRING_NB_OVERFLOW 17   /**<  Too many sub-strings found (more than '%d'). */
#define miscERR_FILE_EXTENSION_UNKNOWN 25   /**<  File extension '.%80s' is not supported; file '%.80s' could not be located. */
#define miscERR_HOST_NOT_FOUND 26   /**<  host '%80s' not found. */
#define miscERR_NO_ADDRESS 27   /**<  the name '%80s' is valid but have no IP address. */
#define miscERR_NO_RECOVERY 28   /**<  a fatal error of the name server append. */
#define miscERR_TRY_AGAIN 29   /**<  a temporary error of the name server append, try again later. */
#define miscERR_BUFFER_OVERFLOW 31   /**<  Buffer size exceeded : '%d' bytes available, '%d' bytes needed. */
#define miscERR_COMMAND_STATUS 33   /**<  '%80s' command exited with status '%d' : please use command's manpage for detailed information. */
#define miscERR_COMMAND_EXEC 34   /**<  '%80s' command could not be performed. */
