/*
 * Error Include File    Created on ...
 *
 * This file has been generated by errXmlToH utility
 * 
 * !!!!!!!!!!!  DO NOT MANUALLY EDIT THIS FILE  !!!!!!!!!!!
 */

 /**
 * \file 
 * Generated file for the define list of errors.
 */
#define envERR_FORMAT_ENVLIST 1   /**<  wrong format of the line '%80s' in environment list file '%80s'; should be 'envName' 'hostName' 'portNumber' */
#define envERR_UNKNOWN_ENV 2   /**<  '%80s' environment is not defined in the environment list file '%80s' */
#define envERR_DUPLICATE_ENV 3   /**<  '%80s' environment is already defined in the environment list file '%80s' */
#define envERR_PORT_ALREADY_USED 4   /**<  port '%d' of envirnoment '%80s' already used by environment '%80s' on '%80s' host */
