/*
 * Error Include File    Created on ...
 *
 * This file has been generated by errXmlToH utility
 * 
 * !!!!!!!!!!!  DO NOT MANUALLY EDIT THIS FILE  !!!!!!!!!!!
 */

 /**
 * \file 
 * Generated file for the define list of errors.
 */
#define errERR_NUM_1 1   /**<  Error number %d (for test purpose only) */
#define errERR_NUM_2 2   /**<  Error number %d (for test purpose only) */
#define errERR_USR_MSG 3   /**<  Error message intended to end-user (for test purpose only) */
