/*
 * Error Include File    Created on ...
 *
 * This file has been generated by errXmlToH utility
 * 
 * !!!!!!!!!!!  DO NOT MANUALLY EDIT THIS FILE  !!!!!!!!!!!
 */

 /**
 * \file 
 * Generated file for the define list of errors.
 */
#define evhERR_NULL_OBJECT 3   /**<  Could not run callback; object not set */
#define evhERR_NULL_METHOD 4   /**<  Could not run callback; method not set */
#define evhERR_RUN_CB 5   /**<  Failure running callback */
#define evhERR_SELECT 6   /**<  Select() call fails - %80s */
#define evhERR_NO_STREAM_TO_LISTEN 8   /**<  No stream (message queue, file descriptor) to listen */
#define evhERR_CMD_UNKNOWN 9   /**<  Unknown command %.20s */
#define evhERR_REPLY 10   /**<  Error reply received from %.80s for command %.80s  */
#define evhERR_NO_HANDLER_INSTANCE 11   /**<  No event handler available */
#define evhERR_DUPLICATED_STATE  12   /**<  Duplicated server state; id=%d - name '%.20s' */
#define evhERR_DUPLICATED_SUBSTATE  13   /**<  Duplicated server sub-state; id=%d - name '%.20s' */
#define evhERR_TIMEOUT_EXPIRED 14   /**<  Timeout expired when waiting for reply of '%80s' command.  */
