/*
 * Error Include File    Created on ...
 *
 * This file has been generated by errXmlToH utility
 * 
 * !!!!!!!!!!!  DO NOT MANUALLY EDIT THIS FILE  !!!!!!!!!!!
 */

#define evhERR_NULL_OBJECT 3   /**<  Could not run callback; object not set */
#define evhERR_NULL_METHOD 4   /**<  Could not run callback; method not set */
#define evhERR_RUN_CB 5   /**<  Failure running callback */
#define evhERR_SELECT 6   /**<  select() call fails - %s */
#define evhERR_NO_STREAM_TO_LISTEN 8   /**<  no stream (message queue, file descriptor) to listen */
