/*
 * ReportDialog.java
 *
 * Created on 16 fevrier 2007, 13:04
 */
package fr.jmmc.mcs.gui;


/**
 *
 * @author  mella
 */
public class ReportDialog extends javax.swing.JDialog
{
    /**
     * DOCUMENT ME!
     */
    private final static String className_ = "ReportDialog";

    /**
     * DOCUMENT ME!
     */
    protected static java.util.logging.Logger logger_ = java.util.logging.Logger.getLogger(
            "fr.jmmc.mcs.gui.ReportDialog");

    /**
     * DOCUMENT ME!
     */
    protected static String defaultEmail = "";

    /**
     * DOCUMENT ME!
     */
    protected static String defaultComment = "";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * DOCUMENT ME!
     */
    private javax.swing.JPanel buttonsPanel;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JButton cancelButton;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JScrollPane commentScrollPane;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JTextArea commentTextArea;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JTextArea detailMsgTextArea;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JScrollPane detailScrollPane;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JToggleButton detailToggleButton;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JTextField emailTextField;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JScrollPane errorMsgScrollPane;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JTextArea errorMsgTextArea;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JButton iconButton;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JPanel jPanel1;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JToggleButton reportToggleButton;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JButton sendBugReportButton;

    /** Creates new form ReportDialog */
    public ReportDialog(java.awt.Frame parent, boolean modal, String errorMsg,
        String detailMsg)
    {
        super(parent, modal);
        initComponents();
        init(errorMsg, detailMsg);
    }

    /** Creates new form ReportDialog  with exception information */
    public ReportDialog(java.awt.Frame parent, boolean modal, Exception e)
    {
        super(parent, modal);
        initComponents();

        // Get stackTrace
        java.io.StringWriter sw = new java.io.StringWriter();
        e.printStackTrace(new java.io.PrintWriter(sw));

        init(e.getMessage(), sw.toString());
    }

    /**
     * DOCUMENT ME!
     *
     * @param errorMsg DOCUMENT ME!
     * @param detailMsg DOCUMENT ME!
     */
    private void init(String errorMsg, String detailMsg)
    {
        logger_.entering("" + this.getClass(), "init");
        logger_.warning(errorMsg);
        errorMsgTextArea.setText(errorMsg);
        detailMsgTextArea.setText(detailMsg);
        emailTextField.setText(defaultEmail);
        emailTextField.setVisible(false);
        commentTextArea.setText(defaultComment);
        commentScrollPane.setVisible(false);
        detailScrollPane.setVisible(false);
        sendBugReportButton.setVisible(false);
        this.setLocationRelativeTo(null);
        pack();
    }

    /**
     * DOCUMENT ME!
     */
    public void sendBugReport()
    {
        logger_.entering("" + this.getClass(), "sendBugReport");

        logger_.info("To Be Implemented: Send Bug report with " + "\nemail=" +
            emailTextField.getText() + "\ncomment=" +
            commentTextArea.getText() + "\nerrorMsg=" +
            errorMsgTextArea.getText() + "\nStack=" +
            detailMsgTextArea.getText());
        dispose();
    }

    /**
     * Use it to define default email.
     *
     * @param email email
     */
    public static void setDefaultEmail(String email)
    {
        logger_.entering(className_, "setDefaultEmail");
        System.out.println("email :" + email);
        defaultEmail = email;
    }

    /**
     * Use it to define default comment
     *
     * @param comment comment
     */
    public static void setDefaultComment(String comment)
    {
        logger_.entering(className_, "setDefaultComment");

        defaultComment = comment;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1                 = new javax.swing.JPanel();
        emailTextField          = new javax.swing.JTextField();
        commentScrollPane       = new javax.swing.JScrollPane();
        commentTextArea         = new javax.swing.JTextArea();
        detailScrollPane        = new javax.swing.JScrollPane();
        detailMsgTextArea       = new javax.swing.JTextArea();
        errorMsgScrollPane      = new javax.swing.JScrollPane();
        errorMsgTextArea        = new javax.swing.JTextArea();
        iconButton              = new javax.swing.JButton();
        buttonsPanel            = new javax.swing.JPanel();
        cancelButton            = new javax.swing.JButton();
        sendBugReportButton     = new javax.swing.JButton();
        detailToggleButton      = new javax.swing.JToggleButton();
        reportToggleButton      = new javax.swing.JToggleButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        emailTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(
                "Email"));
        gridBagConstraints               = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx         = 0;
        gridBagConstraints.gridy         = 4;
        gridBagConstraints.gridwidth     = 2;
        gridBagConstraints.fill          = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx       = 1.0;
        jPanel1.add(emailTextField, gridBagConstraints);

        commentScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(
                "Comments"));
        commentTextArea.setColumns(20);
        commentTextArea.setRows(5);
        commentScrollPane.setViewportView(commentTextArea);

        gridBagConstraints               = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx         = 0;
        gridBagConstraints.gridy         = 5;
        gridBagConstraints.gridwidth     = 2;
        gridBagConstraints.fill          = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx       = 1.0;
        jPanel1.add(commentScrollPane, gridBagConstraints);

        detailMsgTextArea.setColumns(80);
        detailMsgTextArea.setRows(5);
        detailMsgTextArea.setBorder(null);
        detailScrollPane.setViewportView(detailMsgTextArea);

        gridBagConstraints               = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx         = 0;
        gridBagConstraints.gridy         = 2;
        gridBagConstraints.gridwidth     = 2;
        gridBagConstraints.fill          = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx       = 1.0;
        jPanel1.add(detailScrollPane, gridBagConstraints);

        errorMsgTextArea.setColumns(20);
        errorMsgTextArea.setRows(2);
        errorMsgScrollPane.setViewportView(errorMsgTextArea);

        gridBagConstraints           = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx     = 1;
        gridBagConstraints.gridy     = 0;
        gridBagConstraints.fill      = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(errorMsgScrollPane, gridBagConstraints);

        iconButton.setIcon(new javax.swing.ImageIcon(getClass()
                                                         .getResource("/fr/jmmc/mcs/gui/bug_error.png")));
        iconButton.setBorder(null);
        iconButton.setFocusPainted(false);
        iconButton.setFocusable(false);
        gridBagConstraints           = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx     = 0;
        gridBagConstraints.gridy     = 0;
        jPanel1.add(iconButton, gridBagConstraints);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    cancelButtonActionPerformed(evt);
                }
            });

        buttonsPanel.add(cancelButton);

        sendBugReportButton.setText("Send Bug Report");
        sendBugReportButton.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    sendBugReportButtonActionPerformed(evt);
                }
            });

        buttonsPanel.add(sendBugReportButton);

        gridBagConstraints               = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx         = 0;
        gridBagConstraints.gridy         = 6;
        gridBagConstraints.gridwidth     = 2;
        jPanel1.add(buttonsPanel, gridBagConstraints);

        detailToggleButton.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/fr/jmmc/mcs/gui/rightarrow.png")));
        detailToggleButton.setText("Java stack trace");
        detailToggleButton.setBorder(null);
        detailToggleButton.setSelectedIcon(new javax.swing.ImageIcon(
                getClass().getResource("/fr/jmmc/mcs/gui/downarrow.png")));
        detailToggleButton.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    detailToggleButtonActionPerformed(evt);
                }
            });

        gridBagConstraints            = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx      = 0;
        gridBagConstraints.gridy      = 1;
        gridBagConstraints.anchor     = java.awt.GridBagConstraints.WEST;
        jPanel1.add(detailToggleButton, gridBagConstraints);

        reportToggleButton.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/fr/jmmc/mcs/gui/rightarrow.png")));
        reportToggleButton.setText("Report form");
        reportToggleButton.setBorder(null);
        reportToggleButton.setSelectedIcon(new javax.swing.ImageIcon(
                getClass().getResource("/fr/jmmc/mcs/gui/downarrow.png")));
        reportToggleButton.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    reportToggleButtonActionPerformed(evt);
                }
            });

        gridBagConstraints            = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx      = 0;
        gridBagConstraints.gridy      = 3;
        gridBagConstraints.anchor     = java.awt.GridBagConstraints.WEST;
        jPanel1.add(reportToggleButton, gridBagConstraints);

        gridBagConstraints             = new java.awt.GridBagConstraints();
        gridBagConstraints.fill        = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx     = 1.0;
        gridBagConstraints.weighty     = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param evt DOCUMENT ME!
     */
    private void sendBugReportButtonActionPerformed(
        java.awt.event.ActionEvent evt)
    { //GEN-FIRST:event_sendBugReportButtonActionPerformed
        sendBugReport();
    } //GEN-LAST:event_sendBugReportButtonActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param evt DOCUMENT ME!
     */
    private void reportToggleButtonActionPerformed(
        java.awt.event.ActionEvent evt)
    { //GEN-FIRST:event_reportToggleButtonActionPerformed

        boolean flag = reportToggleButton.isSelected();
        commentScrollPane.setVisible(flag);
        emailTextField.setVisible(flag);
        sendBugReportButton.setVisible(flag);
        pack();
        pack();
    } //GEN-LAST:event_reportToggleButtonActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param evt DOCUMENT ME!
     */
    private void detailToggleButtonActionPerformed(
        java.awt.event.ActionEvent evt)
    { //GEN-FIRST:event_detailToggleButtonActionPerformed

        boolean flag = detailToggleButton.isSelected();
        detailScrollPane.setVisible(flag);
        pack();
        pack();
    } //GEN-LAST:event_detailToggleButtonActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param evt DOCUMENT ME!
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)
    { //GEN-FIRST:event_cancelButtonActionPerformed
        logger_.fine("User pressed cancel");
        dispose();
    } //GEN-LAST:event_cancelButtonActionPerformed

    // End of variables declaration//GEN-END:variables
}
