/*
 * ErrorDialog.java
 *
 * Created on 27 juillet 2006, 09:07
 */
package jmmc.mcs.gui;

import java.io.PrintWriter;
import java.io.StringWriter;

import javax.swing.plaf.FileChooserUI;


/**
 *
 * @author  mella
 */
public class ReportDialog extends javax.swing.JDialog
{
    // Variables declaration - do not modify                     
    /**
     * DOCUMENT ME!
     */
    private javax.swing.JTextArea detailMsgTextArea;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JScrollPane detailsScrollPane;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JTextField errorMsgTextField;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JButton jButton1;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JButton jButton2;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JButton jButton3;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JPanel jPanel2;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JPanel jPanel3;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JPanel jPanel4;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JScrollPane jScrollPane2;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JTextArea jTextArea2;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JToggleButton jToggleButton1;

    /** Creates new form ErrorDialog */
    public ReportDialog(java.awt.Frame parent, boolean modal, String errorMsg,
        String detailMsg)
    {
        super(parent, modal);
        initComponents();
        errorMsgTextField.setText(errorMsg);
        detailMsgTextArea.setText(detailMsg);
        detailsScrollPane.setVisible(false);
        pack();

        //this.setLocationRelativeTo(null);        
    }

    /** Creates new form ErrorDialog  with exception information */
    public ReportDialog(java.awt.Frame parent, boolean modal, Exception e)
    {
        super(parent, modal);
        initComponents();

        // Get message
        errorMsgTextField.setText(e.getMessage());

        // Get stackTrace
        StringWriter sw = new StringWriter();
        e.printStackTrace(new PrintWriter(sw));
        detailMsgTextArea.setText(sw.toString());

        detailsScrollPane.setVisible(false);
        pack();

        //this.setLocationRelativeTo(null);        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4               = new javax.swing.JPanel();
        jPanel2               = new javax.swing.JPanel();
        jButton1              = new javax.swing.JButton();
        errorMsgTextField     = new javax.swing.JTextField();
        jToggleButton1        = new javax.swing.JToggleButton();
        detailsScrollPane     = new javax.swing.JScrollPane();
        detailMsgTextArea     = new javax.swing.JTextArea();
        jScrollPane2          = new javax.swing.JScrollPane();
        jTextArea2            = new javax.swing.JTextArea();
        jPanel3               = new javax.swing.JPanel();
        jButton2              = new javax.swing.JButton();
        jButton3              = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.BorderLayout(2, 2));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Software error report");
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4,
                javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2,
                javax.swing.BoxLayout.X_AXIS));

        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 29));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass()
                                                       .getResource("/jmmc/mcs/gui/bug_error.png")));
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton1.setPreferredSize(new java.awt.Dimension(32, 32));
        jPanel2.add(jButton1);

        errorMsgTextField.setEditable(false);
        errorMsgTextField.setText("jTextField1");
        errorMsgTextField.setBorder(null);
        errorMsgTextField.setFocusable(false);
        jPanel2.add(errorMsgTextField);

        jPanel4.add(jPanel2);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass()
                                                             .getResource("/jmmc/mcs/gui/rightarrow.png")));
        jToggleButton1.setBorder(null);
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jToggleButton1.setSelectedIcon(new javax.swing.ImageIcon(
                getClass().getResource("/jmmc/mcs/gui/downarrow.png")));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    jToggleButton1ActionPerformed(evt);
                }
            });

        jPanel4.add(jToggleButton1);

        detailsScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(
                "Details"));
        detailsScrollPane.setMaximumSize(null);
        detailsScrollPane.setPreferredSize(new java.awt.Dimension(700, 150));
        detailMsgTextArea.setBackground(javax.swing.UIManager.getDefaults()
                                                             .getColor("Button.background"));
        detailMsgTextArea.setColumns(20);
        detailMsgTextArea.setRows(5);
        detailMsgTextArea.setMaximumSize(null);
        detailsScrollPane.setViewportView(detailMsgTextArea);

        jPanel4.add(detailsScrollPane);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(
                "Comments"));
        jScrollPane2.setMaximumSize(null);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(700, 116));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel4.add(jScrollPane2);

        jButton2.setText("Report");
        jButton2.setAlignmentX(0.5F);
        jPanel3.add(jButton2);

        jButton3.setText("Ignore");
        jButton3.setAlignmentX(0.5F);
        jPanel3.add(jButton3);

        jPanel4.add(jPanel3);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }

    // </editor-fold>//GEN-END:initComponents
    /**
     * DOCUMENT ME!
     *
     * @param evt DOCUMENT ME!
     */
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_jToggleButton1ActionPerformed
        detailsScrollPane.setVisible(jToggleButton1.isSelected());
        pack();
        pack();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args)
    {
        java.awt.EventQueue.invokeLater(new Runnable()
            {
                public void run()
                {
                    try
                    {
                        java.io.File f = new java.io.File("fdljkfdlhsdqfjh cqs");
                        f.getCanonicalPath();
                    }
                    catch (Exception e)
                    {
                        new ReportDialog(new javax.swing.JFrame(), true, e).setVisible(true);
                    }
                }
            });
    }

    // End of variables declaration                   
}
