<?xml version="1.0" encoding="ISO-8859-1"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output method="text"/>

    <xsl:variable name="modName">
        <xsl:value-of select="//@moduleName"/>
    </xsl:variable>

    <xsl:template match="/">

        <!-- Print Header -->

<xsl:text>/*
 * Error Include File    Created on ...
 *
 * This file has been generated by errXmlToH utility
 * 
 * !!!!!!!!!!!  DO NOT MANUALLY EDIT THIS FILE  !!!!!!!!!!!
 */

</xsl:text>

        <!-- For each error print associated define with doxygen comment-->

        <xsl:for-each select="//error">
            <xsl:text>#define </xsl:text>
            <xsl:value-of select="$modName" />
            <xsl:text>ERR_</xsl:text>
            <xsl:value-of select="errName" />
            <xsl:text> </xsl:text>
            <xsl:value-of select="@id" />
            <xsl:text>   /**&lt;  </xsl:text>
            <xsl:value-of select="errFormat" />
            <xsl:text> */&#xA;</xsl:text>
        </xsl:for-each>
    </xsl:template>


</xsl:stylesheet>
