/*
 * Error Include File    Created on ...
 *
 * This file has been generated by errXmlToH utility
 * 
 * !!!!!!!!!!!  DO NOT MANUALLY EDIT THIS FILE  !!!!!!!!!!!
 */

 /**
 * \file 
 * Generated file for the define list of errors.
 */
#define sdbERR_NULL_PARAM 1   /**<  Received a NULL value for parameter '%80s'. */
#define sdbERR_TIMEOUT_EXPIRED 2   /**<  Timeout expired when waiting for new message. */
