/*
 * Error Include File    Created on ...
 *
 * This file has been generated by errXmlToH utility
 * 
 * !!!!!!!!!!!  DO NOT MANUALLY EDIT THIS FILE  !!!!!!!!!!!
 */

 /**
 * \file 
 * Generated file for the define list of errors.
 */
#define thrdERR_NULL_PARAM 1   /**<  Received a NULL value for parameter '%80s'. */
#define thrdERR_ASSERT_FAILED 2   /**<  Assertion failed. */
#define thrdERR_THREAD_NUMBER 3   /**<  There is no system resources left to create a new thread. */
#define thrdERR_THREAD_NOT_FOUND 4   /**<  The thread with id '%d' was not found. */
#define thrdERR_THREAD_DETACHED 5   /**<  The thread with id '%d' has already been detached, or another thread is already waiting on its termination. */
#define thrdERR_THREAD_DEADLOCK 6   /**<  The thread with id '%d' refers to itself, leadind to a dead lock. */
#define thrdERR_MUTEX_INIT 7   /**<  The mutex could not be created. */
#define thrdERR_MUTEX_NOT_INIT 9   /**<  The mutex has not been properly initialized. */
#define thrdERR_MUTEX_LOCKED 8   /**<  The mutex is locked. */
#define thrdERR_ERRNO 10   /**<  System call '%.100s' error : errno='%.100s' -&gt; '%.100s'. */
