/*
 * Error Include File    Created on ...
 *
 * This file has been generated by errXmlToH utility
 * 
 * !!!!!!!!!!!  DO NOT MANUALLY EDIT THIS FILE  !!!!!!!!!!!
 */

 /**
 * \file 
 * Generated file for the define list of errors.
 */
#define timlogERR_ALLOC_MEM 1   /**<  Could not allocate memory */
#define timlogERR_NO_TIME_MARKER 2   /**<  Start time marker '%.80s' is not defined into timer logging service. */
#define timlogERR_HASH_MUTEX 3   /**<  Could not use mutex that prevents concurrent access to hash table shared object */
