#!/bin/bash
#*******************************************************************************
# JMMC project
#
# "@(#) $Id: jmcsHTML2HelpSet.sh,v 1.1 2008-04-29 14:28:58 bcolucci Exp $"
#
# History
# -------
# $Log: not supported by cvs2svn $
#*******************************************************************************

#/**
# @file
# Generates a HelpSet Jar file which contains .hs, .jhm and .toc files from
# a HTML folder. This shell script uses java script jmcsGenerateHelpsetFromHtml and jhelpdev software.
#
# @synopsis
# jmcsHTML2HelpSet [Folder] [JarExportFolder]
#
# @param Folder : Path of the HTML Folder to convert
# @param JarExportFolder : Path of the Jar export folder
# 
# @usedfiles
# @filename fr.jmcs.mcs.gui.jmcsGenerateHelpsetFromHtml : Calls the fonctions used to create .hs, .jhm and .toc files
#
# @env
# @envvar envVar1 :  usage description of envVar1
# @envvar envVar2 :  usage description of envVar2
# 
# @ex
# @code
# ./jmcsHTML2HelpSet.sh /home/xxx/yyy/htmlFolderToConvert
# @endcode
# */


# signal trap (if any)

#Checks that there is only 1 argument (the html folder path)

header="<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE jhelpdev PUBLIC \"-//jhelpdev.sourcefore.net//JHelpDev Configuration Settings 1.2\" \"http://jhelpdev.sourceforge.net/dtd/jhelpdev_1_2.dtd\"><!--generated by JHelpDev Version: 0.62, 10 November 2006, see jhelpdev.sourceforge.org--><jhelpdev version=\"1.2\"><config><project>documentation</project><projectdir>"
footer="</projectdir><startpage>index.html</startpage><popupicon></popupicon></config><view> <helptitle>Help</helptitle><toc showing=\"yes\" label=\"TOC\"/><index showing=\"yes\" label=\"Index\"/><search showing=\"yes\" label=\"Search\"/></view><encoding value=\"UTF-8\"/></jhelpdev>"

tmp_folder=../doc/tmp
cvs_root=cvslaog.obs.ujf-grenoble.fr:/cvs/doc
module_name=$(ctooGetModuleName)
jar_name=$module_name"-doc.jar"
jar_path=../../lib/$jar_name
jhelpdev_tmp_folder=/tmp/JavaHelpSearch

if [ $# -ge 1 ]; then

    clear
    echo "Actual path : $(pwd)"

    # Exportes CVSROOT in order to checkout modules
    export CVSROOT=$cvs_root
    echo "CVSROOT exported : $cvs_root ..."

    # Removes tmp folder if exists
    if [ -e $tmp_folder ]; then
        if [ -d $tmp_folder ]; then
            rm -rf $tmp_folder
            echo "Folder : $tmp_folder removed ..."
        fi
    fi

    # Creates tmp folder
    mkdir $tmp_folder
    echo "Folder : $tmp_folder created ..."

    # Goes in tmp folder
    cd $tmp_folder
    echo "Path has changed : $(pwd)"

    # For each module
    for module in $@
    do
        clear

        # CVS Checkout
        cvs co $module

        # Goes in the module folder
        # and compiles it
        cd $module
        echo "Path has changed : $(pwd)"
        clear
        make

        clear

        # Moves content of checkout folder
        for module_file in $(ls $module/*)
        do
            mv -f $module_file .
            echo "File : $module_file moved ..."
        done
        rm -rf $module_file
        echo "Folder : $module_file removed ..."

        # Cleans some latex files unused in helpset
        rm -f *.aux *.tex *.toc *.pdf *.dvi *.info *.log *.out *.pl *.bb *.css *.sty Makefile
        rm -rf CVS
        echo "Path  $(pwd) cleaned ..."

        # Returns in tmp folder
        cd ..
        echo "Path has changed : $(pwd)"
    done

    clear

    # Created the jhelpdev XML project file
    touch documentation.xml
    echo $header$(pwd)$footer > documentation.xml 
    echo "File : documentation.xml created ..."

    # Launches jhelpdev
    java -classpath $(mkfMakeJavaClasspath) fr.jmmc.mcs.gui.jmcsGenerateHelpsetFromHtml documentation.xml

    clear

    # Checks if the jar exists
    if [ -e $jar_path ]; then
        rm -f $jar_path
        echo "File : $jar_path removed ..."
    fi
    
    # Creates je jar file
    jar -cf $jar_name *
    echo "File : $jar_name created ..."

    # Moves it into lib folder
    mv $jar_name ../../lib
    echo "File : $jar_name moved into ../../lib ..."

    # Returns to .. and remove tmp folder
    cd ..
    echo "Path has changed : $(pwd)"
    rm -rf tmp
    echo "Folder : $tmp_folder removed ..."

    # Removes jhelpdev tmp folder if exists
    if [ -e $jhelpdev_tmp_folder ]; then
        if [ -d $jhelpdev_tmp_folder ]; then
            rm -rf $jhelpdev_tmp_folder
            echo "Folder : $jhelpdev_tmp_folder removed ..."
        fi
    fi
else
    echo "Error : Please specify one module at least ..."

fi

clear
echo "|===================>> Terminated ..."

#___oOo___
