/*
 * Error Include File    Created on ...
 *
 * This file has been generated by errXmlToH utility
 * 
 * !!!!!!!!!!!  DO NOT MANUALLY EDIT THIS FILE  !!!!!!!!!!!
 */

 /**
 * \file 
 * Generated file for the define list of errors.
 */
#define cmdERR_STRING_FORMAT 1   /**<  Incorrect '%.80s' string format : missing or redundant '"' */
#define cmdERR_MALLOC 2   /**<  Memory allocation error */
#define cmdERR_PARAMS_FORMAT 3   /**<  Incorrect '%.80s' parameter format : must be '-param1' 'value1' '-param2' 'value2'... */
#define cmdERR_PARAM_NAME 4   /**<  Incorrect '%.80s' parameter name : must begin with '-' */
#define cmdERR_PARAM_INDEX 5   /**<  '%d' position is out-of-range [0-%d] */
#define cmdERR_PARAM_NOT_FOUND 6   /**<  '%.80s' parameter could not be found */
#define cmdERR_LOGICAL_VALUE 7   /**<  Incorrect '%.80s' boolean value for '%.80s' parameter */
#define cmdERR_INTEGER_VALUE 8   /**<  Incorrect '%.80s' integer value for '%.80s' parameter */
#define cmdERR_DOUBLE_VALUE 9   /**<  Incorrect '%.80s' float value for '%.80s' parameter */
#define cmdERR_UNUSED_PARAM 10   /**<  '%.80s' parameter has not been recognize */
#define cmdERR_MISSING_PARAM 11   /**<  '%.80s' parameter is missing for command %.80s */
#define cmdERR_PARAM_UNKNOWN 12   /**<  Invalid parameter name '%.80s' for command %.80s */
#define cmdERR_PARSE_PARAMETERS 13   /**<  Could not parse parameters '%.80s' for command %.20s.  */
#define cmdERR_PARSE_CDF 14   /**<  Could not parse command definition file '%.80s' for command %.80s.  */
#define cmdERR_NO_CDF 15   /**<  No command definition file for command %.80s. Command could not be parsed. */
#define cmdERR_CDF_NO_ELEMENT_CONTENT 16   /**<  Illegal format encountered for CDF file - no content for '%.20s' element */
#define cmdERR_CDF_FORMAT 17   /**<  Illegal format encountered for CDF file - loading CDF '%.80s' failed with exeption #%d  */
#define cmdERR_CDF_FORMAT_ITEM 18   /**<  Illegal format encountered for CDF file - get %dth item of  element '%.20s' failed with exception #%d  */
#define cmdERR_CDF_FORMAT_ELEMENT  19   /**<  Illegal format encountered for CDF file - get element '%.20s' failed with exception #%d  */
#define cmdERR_CDF_FORMAT_CONTENT  20   /**<  Illegal format encountered for CDF file - get content of '%.20s' element failed with exception #%d  */
#define cmdERR_DEFAULTVALUE_FORMAT 21   /**<  Invalid format for default value of '%.40s' parameter */
#define cmdERR_CDF_NO_NODE_ELEMENT 22   /**<  Illegal format encountered for CDF file - missing '%.20s' node */
#define cmdERR_VALUE_OUT_OF_RANGE 23   /**<  Value '%.40s' of '%.40s' parameter is out of range; should be %.40s than '%.40s' */
