/*
 * Error Include File    Created on ...
 *
 * This file has been generated by errXmlToH utility
 * 
 * !!!!!!!!!!!  DO NOT MANUALLY EDIT THIS FILE  !!!!!!!!!!!
 */

 /**
 * \file 
 * Generated file for the define list of errors.
 */
#define msgERR_SOCKET 1   /**<  socket() call error - %80s */
#define msgERR_BIND 2   /**<  bind() call error - %80s */
#define msgERR_GETSOCKNAME 3   /**<  getsockname() call error - %80s */
#define msgERR_MCSINIT 4   /**<  mcsInit() call error - %80s */
#define msgERR_GETHOSTBYNAME 5   /**<  gethostbyname() call error - %80s */
#define msgERR_CONNECT 6   /**<  connect() call error - %80s */
#define msgERR_MALLOC 7   /**<  malloc() call error - %80s */
#define msgERR_EMPTY_PROCLIST 8   /**<  process list is empty - %80s */
#define msgERR_PROC_NOT_FOUND 9   /**<  '%80s' process not found in the process list */
#define msgERR_PROC_ALREADY_CONNECTED 10   /**<  connection to the communication server is already established */
#define msgERR_PROC_NOT_CONNECTED 11   /**<  process is not connected to the communication server */
#define msgERR_SEND 12   /**<  send() call error - %80s */
#define msgERR_PARTIAL_SEND 13   /**<  message partialy sent (%d bytes instead of %d) - %80s */
#define msgERR_TIMEOUT_EXPIRED 14   /**<  timeout expired when waiting for message */
#define msgERR_SELECT 15   /**<  select() call error - %80s */
#define msgERR_BROKEN_PIPE 16   /**<  connection with remote process lost */
#define msgERR_PARTIAL_HDR_RECV 17   /**<  message header partialy received (%d bytes instead of %d) */
#define msgERR_PARTIAL_BODY_RECV 18   /**<  message body partialy received (%d bytes instead of %d) */
#define msgERR_DUPLICATE_PROC 19   /**<  a '%80s'-named process is already connected */
#define msgERR_CMD_NOT_SUPPORTED 21   /**<  '%80s' command is not supported by the communication server */
#define msgERR_RECIPIENT_NOT_CONNECTED 22   /**<  '%80s' remote process, recipient of the '%80s' command, is not reachable */
#define msgERR_MSG_TYPE 23   /**<  incorrect %d message type */
#define msgERR_PING 24   /**<  '%80s' remote process is not reachable */
#define msgERR_SENDER_NOT_CONNECTED 25   /**<  '%80s' process, sender of the '%80s' command, is not connected */
#define msgERR_BUFFER_TOO_BIG 26   /**<  %d bytes buffer size is too big (max = %d) */
#define msgERR_SOCKET_NOT_CONNECTED 27   /**<  socket not connected */
#define msgERR_LISTEN 28   /**<  listen() call error - %80s */
#define msgERR_RECV 29   /**<  recv() call error - %80s */
#define msgERR_EMPTY_STACK 36   /**<  empty stack */
#define msgERR_FORMAT_ENVLIST 32   /**<  wrong format of the line '%80s' in environment list file '%80s'; should be 'envName' 'hostName' 'portNumber' */
#define msgERR_UNKNOWN_ENV 31   /**<  '%80s' environment is not defined in the environment list file '%80s' */
#define msgERR_REMOTE_ENV 33   /**<  connection with '%80s' remote environment running on '%80s' is not allowed */
#define msgERR_NULL_PARAM 34   /**<  Received a NULL value for parameter '%.80s'. */
#define msgERR_PROC_ABNORMALLY_EXIT 35   /**<  Process %80s whose an answer was awaited, abnormally exit */
#define msgERR_REPLY_TIMEOUT_EXPIRED 37   /**<  timeout expired when waiting for %80s command reply */
